// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const assignDeploymentToWorker = `-- name: AssignDeploymentToWorker :exec
UPDATE deployments SET worker_id = ?, state = 'assigned', updated_at = datetime('now') WHERE id = ?
`

type AssignDeploymentToWorkerParams struct {
	WorkerID sql.NullInt64 `db:"worker_id" json:"worker_id"`
	ID       int64         `db:"id" json:"id"`
}

func (q *Queries) AssignDeploymentToWorker(ctx context.Context, arg AssignDeploymentToWorkerParams) error {
	_, err := q.db.ExecContext(ctx, assignDeploymentToWorker, arg.WorkerID, arg.ID)
	return err
}

const completeDeployment = `-- name: CompleteDeployment :exec
UPDATE deployments SET state = ?, container_id = ?, preview_url = ?, completed_at = datetime('now'), updated_at = datetime('now') WHERE id = ?
`

type CompleteDeploymentParams struct {
	State       string         `db:"state" json:"state"`
	ContainerID sql.NullString `db:"container_id" json:"container_id"`
	PreviewUrl  sql.NullString `db:"preview_url" json:"preview_url"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) CompleteDeployment(ctx context.Context, arg CompleteDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, completeDeployment,
		arg.State,
		arg.ContainerID,
		arg.PreviewUrl,
		arg.ID,
	)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (project_id, pr_number, commit_sha, branch, state)
VALUES (?, ?, ?, ?, 'queued')
RETURNING id, project_id, pr_number, commit_sha, branch, state, created_at, updated_at
`

type CreateDeploymentParams struct {
	ProjectID int64  `db:"project_id" json:"project_id"`
	PrNumber  int64  `db:"pr_number" json:"pr_number"`
	CommitSha string `db:"commit_sha" json:"commit_sha"`
	Branch    string `db:"branch" json:"branch"`
}

type CreateDeploymentRow struct {
	ID        int64        `db:"id" json:"id"`
	ProjectID int64        `db:"project_id" json:"project_id"`
	PrNumber  int64        `db:"pr_number" json:"pr_number"`
	CommitSha string       `db:"commit_sha" json:"commit_sha"`
	Branch    string       `db:"branch" json:"branch"`
	State     string       `db:"state" json:"state"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (CreateDeploymentRow, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.ProjectID,
		arg.PrNumber,
		arg.CommitSha,
		arg.Branch,
	)
	var i CreateDeploymentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PrNumber,
		&i.CommitSha,
		&i.Branch,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeploymentFromWebhook = `-- name: CreateDeploymentFromWebhook :one
INSERT INTO deployments (project_id, pr_number, commit_sha, branch, state, preview_url)
VALUES (?, ?, ?, ?, 'queued', ?)
RETURNING id
`

type CreateDeploymentFromWebhookParams struct {
	ProjectID  int64          `db:"project_id" json:"project_id"`
	PrNumber   int64          `db:"pr_number" json:"pr_number"`
	CommitSha  string         `db:"commit_sha" json:"commit_sha"`
	Branch     string         `db:"branch" json:"branch"`
	PreviewUrl sql.NullString `db:"preview_url" json:"preview_url"`
}

func (q *Queries) CreateDeploymentFromWebhook(ctx context.Context, arg CreateDeploymentFromWebhookParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDeploymentFromWebhook,
		arg.ProjectID,
		arg.PrNumber,
		arg.CommitSha,
		arg.Branch,
		arg.PreviewUrl,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createDeploymentLog = `-- name: CreateDeploymentLog :exec
INSERT INTO deployment_logs (deployment_id, level, message, source) VALUES (?, ?, ?, ?)
`

type CreateDeploymentLogParams struct {
	DeploymentID int64  `db:"deployment_id" json:"deployment_id"`
	Level        string `db:"level" json:"level"`
	Message      string `db:"message" json:"message"`
	Source       string `db:"source" json:"source"`
}

func (q *Queries) CreateDeploymentLog(ctx context.Context, arg CreateDeploymentLogParams) error {
	_, err := q.db.ExecContext(ctx, createDeploymentLog,
		arg.DeploymentID,
		arg.Level,
		arg.Message,
		arg.Source,
	)
	return err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (user_id, name) VALUES (?, ?) RETURNING id
`

type CreateDomainParams struct {
	UserID int64  `db:"user_id" json:"user_id"`
	Name   string `db:"name" json:"name"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDomain, arg.UserID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, name, github_repo, github_repo_id, webhook_secret)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, name, github_repo, github_repo_id, created_at, updated_at
`

type CreateProjectParams struct {
	UserID        int64  `db:"user_id" json:"user_id"`
	Name          string `db:"name" json:"name"`
	GithubRepo    string `db:"github_repo" json:"github_repo"`
	GithubRepoID  int64  `db:"github_repo_id" json:"github_repo_id"`
	WebhookSecret string `db:"webhook_secret" json:"webhook_secret"`
}

type CreateProjectRow struct {
	ID           int64        `db:"id" json:"id"`
	UserID       int64        `db:"user_id" json:"user_id"`
	Name         string       `db:"name" json:"name"`
	GithubRepo   string       `db:"github_repo" json:"github_repo"`
	GithubRepoID int64        `db:"github_repo_id" json:"github_repo_id"`
	CreatedAt    sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt    sql.NullTime `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.UserID,
		arg.Name,
		arg.GithubRepo,
		arg.GithubRepoID,
		arg.WebhookSecret,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.GithubRepo,
		&i.GithubRepoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectDomain = `-- name: CreateProjectDomain :one
INSERT INTO project_domains (project_id, domain_id, prefix) VALUES (?, ?, ?) RETURNING id
`

type CreateProjectDomainParams struct {
	ProjectID int64  `db:"project_id" json:"project_id"`
	DomainID  int64  `db:"domain_id" json:"domain_id"`
	Prefix    string `db:"prefix" json:"prefix"`
}

func (q *Queries) CreateProjectDomain(ctx context.Context, arg CreateProjectDomainParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createProjectDomain, arg.ProjectID, arg.DomainID, arg.Prefix)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, token, expires_at) VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string    `db:"id" json:"id"`
	UserID    int64     `db:"user_id" json:"user_id"`
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash)
VALUES (?, ?)
RETURNING id, username, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `db:"username" json:"username"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

type CreateUserRow struct {
	ID        int64        `db:"id" json:"id"`
	Username  string       `db:"username" json:"username"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (name, address, state, capacity, current_load, capabilities)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, address, state, capacity, current_load, created_at, updated_at
`

type CreateWorkerParams struct {
	Name         string `db:"name" json:"name"`
	Address      string `db:"address" json:"address"`
	State        string `db:"state" json:"state"`
	Capacity     int64  `db:"capacity" json:"capacity"`
	CurrentLoad  int64  `db:"current_load" json:"current_load"`
	Capabilities string `db:"capabilities" json:"capabilities"`
}

type CreateWorkerRow struct {
	ID          int64        `db:"id" json:"id"`
	Name        string       `db:"name" json:"name"`
	Address     string       `db:"address" json:"address"`
	State       string       `db:"state" json:"state"`
	Capacity    int64        `db:"capacity" json:"capacity"`
	CurrentLoad int64        `db:"current_load" json:"current_load"`
	CreatedAt   sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (CreateWorkerRow, error) {
	row := q.db.QueryRowContext(ctx, createWorker,
		arg.Name,
		arg.Address,
		arg.State,
		arg.Capacity,
		arg.CurrentLoad,
		arg.Capabilities,
	)
	var i CreateWorkerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.State,
		&i.Capacity,
		&i.CurrentLoad,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployments WHERE id = ?
`

func (q *Queries) DeleteDeployment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeployment, id)
	return err
}

const deleteDeploymentLogs = `-- name: DeleteDeploymentLogs :exec
DELETE FROM deployment_logs WHERE deployment_id = ?
`

func (q *Queries) DeleteDeploymentLogs(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeploymentLogs, deploymentID)
	return err
}

const deleteDomainByIDAndUser = `-- name: DeleteDomainByIDAndUser :exec
DELETE FROM domains WHERE id = ? AND user_id = ?
`

type DeleteDomainByIDAndUserParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteDomainByIDAndUser(ctx context.Context, arg DeleteDomainByIDAndUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteDomainByIDAndUser, arg.ID, arg.UserID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteOldDeploymentLogs = `-- name: DeleteOldDeploymentLogs :exec
DELETE FROM deployment_logs WHERE timestamp < datetime('now', ? || ' days')
`

func (q *Queries) DeleteOldDeploymentLogs(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteOldDeploymentLogs, dollar_1)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteProjectDomain = `-- name: DeleteProjectDomain :exec
DELETE FROM project_domains WHERE domain_id = ? AND project_id = ?
`

type DeleteProjectDomainParams struct {
	DomainID  int64 `db:"domain_id" json:"domain_id"`
	ProjectID int64 `db:"project_id" json:"project_id"`
}

func (q *Queries) DeleteProjectDomain(ctx context.Context, arg DeleteProjectDomainParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectDomain, arg.DomainID, arg.ProjectID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM workers WHERE id = ?
`

func (q *Queries) DeleteWorker(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWorker, id)
	return err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, project_id, worker_id, pr_number, commit_sha, branch, state, preview_url, container_id, build_log_path, error_message, attempt, created_at, updated_at, started_at, completed_at FROM deployments WHERE id = ?
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id int64) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkerID,
		&i.PrNumber,
		&i.CommitSha,
		&i.Branch,
		&i.State,
		&i.PreviewUrl,
		&i.ContainerID,
		&i.BuildLogPath,
		&i.ErrorMessage,
		&i.Attempt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDeploymentByProjectAndPR = `-- name: GetDeploymentByProjectAndPR :one
SELECT id FROM deployments WHERE project_id = ? AND pr_number = ?
`

type GetDeploymentByProjectAndPRParams struct {
	ProjectID int64 `db:"project_id" json:"project_id"`
	PrNumber  int64 `db:"pr_number" json:"pr_number"`
}

func (q *Queries) GetDeploymentByProjectAndPR(ctx context.Context, arg GetDeploymentByProjectAndPRParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByProjectAndPR, arg.ProjectID, arg.PrNumber)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getDeploymentForUpdate = `-- name: GetDeploymentForUpdate :one
SELECT id, state FROM deployments WHERE project_id = ? AND pr_number = ?
`

type GetDeploymentForUpdateParams struct {
	ProjectID int64 `db:"project_id" json:"project_id"`
	PrNumber  int64 `db:"pr_number" json:"pr_number"`
}

type GetDeploymentForUpdateRow struct {
	ID    int64  `db:"id" json:"id"`
	State string `db:"state" json:"state"`
}

func (q *Queries) GetDeploymentForUpdate(ctx context.Context, arg GetDeploymentForUpdateParams) (GetDeploymentForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentForUpdate, arg.ProjectID, arg.PrNumber)
	var i GetDeploymentForUpdateRow
	err := row.Scan(&i.ID, &i.State)
	return i, err
}

const getDeploymentLogs = `-- name: GetDeploymentLogs :many
SELECT id, deployment_id, level, message, source, timestamp FROM deployment_logs WHERE deployment_id = ? ORDER BY timestamp ASC
`

func (q *Queries) GetDeploymentLogs(ctx context.Context, deploymentID int64) ([]DeploymentLog, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentLogs, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentLog{}
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Level,
			&i.Message,
			&i.Source,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeploymentLogsByLevel = `-- name: GetDeploymentLogsByLevel :many
SELECT id, deployment_id, level, message, source, timestamp FROM deployment_logs WHERE deployment_id = ? AND level = ? ORDER BY timestamp ASC
`

type GetDeploymentLogsByLevelParams struct {
	DeploymentID int64  `db:"deployment_id" json:"deployment_id"`
	Level        string `db:"level" json:"level"`
}

func (q *Queries) GetDeploymentLogsByLevel(ctx context.Context, arg GetDeploymentLogsByLevelParams) ([]DeploymentLog, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentLogsByLevel, arg.DeploymentID, arg.Level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentLog{}
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Level,
			&i.Message,
			&i.Source,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomainByID = `-- name: GetDomainByID :one
SELECT user_id FROM domains WHERE id = ?
`

func (q *Queries) GetDomainByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDomainByID, id)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getProjectByGithubRepo = `-- name: GetProjectByGithubRepo :one
SELECT id FROM projects WHERE github_repo = ?
`

func (q *Queries) GetProjectByGithubRepo(ctx context.Context, githubRepo string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProjectByGithubRepo, githubRepo)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, user_id, name, github_repo, github_repo_id, webhook_secret, created_at, updated_at FROM projects WHERE id = ?
`

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.GithubRepo,
		&i.GithubRepoID,
		&i.WebhookSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectDomainByProjectID = `-- name: GetProjectDomainByProjectID :one
SELECT pd.prefix, d.name
FROM project_domains pd
INNER JOIN domains d ON pd.domain_id = d.id
WHERE pd.project_id = ? LIMIT 1
`

type GetProjectDomainByProjectIDRow struct {
	Prefix string `db:"prefix" json:"prefix"`
	Name   string `db:"name" json:"name"`
}

func (q *Queries) GetProjectDomainByProjectID(ctx context.Context, projectID int64) (GetProjectDomainByProjectIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectDomainByProjectID, projectID)
	var i GetProjectDomainByProjectIDRow
	err := row.Scan(&i.Prefix, &i.Name)
	return i, err
}

const getProjectOwnerByID = `-- name: GetProjectOwnerByID :one
SELECT user_id FROM projects WHERE id = ?
`

func (q *Queries) GetProjectOwnerByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProjectOwnerByID, id)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT user_id FROM sessions WHERE token = ? AND expires_at > datetime('now')
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySessionToken = `-- name: GetUserBySessionToken :one
SELECT u.id, u.username, u.created_at
FROM users u
INNER JOIN sessions s ON u.id = s.user_id
WHERE s.token = ? AND s.expires_at > datetime('now')
`

type GetUserBySessionTokenRow struct {
	ID        int64        `db:"id" json:"id"`
	Username  string       `db:"username" json:"username"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

func (q *Queries) GetUserBySessionToken(ctx context.Context, token string) (GetUserBySessionTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserBySessionToken, token)
	var i GetUserBySessionTokenRow
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at, updated_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCredentials = `-- name: GetUserCredentials :one
SELECT id, password_hash FROM users WHERE username = ?
`

type GetUserCredentialsRow struct {
	ID           int64  `db:"id" json:"id"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) GetUserCredentials(ctx context.Context, username string) (GetUserCredentialsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserCredentials, username)
	var i GetUserCredentialsRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getWorkerByID = `-- name: GetWorkerByID :one
SELECT id, name, address, state, capacity, current_load, capabilities, last_seen_at, created_at, updated_at FROM workers WHERE id = ?
`

func (q *Queries) GetWorkerByID(ctx context.Context, id int64) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorkerByID, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.State,
		&i.Capacity,
		&i.CurrentLoad,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkerByName = `-- name: GetWorkerByName :one
SELECT id, name, address, state, capacity, current_load, capabilities, last_seen_at, created_at, updated_at FROM workers WHERE name = ?
`

func (q *Queries) GetWorkerByName(ctx context.Context, name string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorkerByName, name)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.State,
		&i.Capacity,
		&i.CurrentLoad,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllWorkers = `-- name: ListAllWorkers :many
SELECT id, name, address, state, capacity, current_load, capabilities, last_seen_at, created_at, updated_at FROM workers ORDER BY id
`

func (q *Queries) ListAllWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, listAllWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.State,
			&i.Capacity,
			&i.CurrentLoad,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByProjectID = `-- name: ListDeploymentsByProjectID :many
SELECT id, project_id, worker_id, pr_number, commit_sha, branch, state, preview_url, container_id, build_log_path, error_message, attempt, created_at, updated_at, started_at, completed_at FROM deployments WHERE project_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByProjectID(ctx context.Context, projectID int64) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WorkerID,
			&i.PrNumber,
			&i.CommitSha,
			&i.Branch,
			&i.State,
			&i.PreviewUrl,
			&i.ContainerID,
			&i.BuildLogPath,
			&i.ErrorMessage,
			&i.Attempt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByState = `-- name: ListDeploymentsByState :many
SELECT id, project_id, worker_id, pr_number, commit_sha, branch, state, preview_url, container_id, build_log_path, error_message, attempt, created_at, updated_at, started_at, completed_at FROM deployments WHERE state = ? ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByState(ctx context.Context, state string) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WorkerID,
			&i.PrNumber,
			&i.CommitSha,
			&i.Branch,
			&i.State,
			&i.PreviewUrl,
			&i.ContainerID,
			&i.BuildLogPath,
			&i.ErrorMessage,
			&i.Attempt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByWorkerID = `-- name: ListDeploymentsByWorkerID :many
SELECT id, project_id, worker_id, pr_number, commit_sha, branch, state, preview_url, container_id, build_log_path, error_message, attempt, created_at, updated_at, started_at, completed_at FROM deployments WHERE worker_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByWorkerID(ctx context.Context, workerID sql.NullInt64) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsByWorkerID, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WorkerID,
			&i.PrNumber,
			&i.CommitSha,
			&i.Branch,
			&i.State,
			&i.PreviewUrl,
			&i.ContainerID,
			&i.BuildLogPath,
			&i.ErrorMessage,
			&i.Attempt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsByUserID = `-- name: ListDomainsByUserID :many
SELECT id, user_id, name, created_at, updated_at FROM domains WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDomainsByUserID(ctx context.Context, userID int64) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, listDomainsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnlineWorkers = `-- name: ListOnlineWorkers :many
SELECT id, name, address, state, capacity, current_load, capabilities, last_seen_at, created_at, updated_at FROM workers WHERE state = 'online' AND last_seen_at > datetime('now', '-45 seconds')
`

func (q *Queries) ListOnlineWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, listOnlineWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.State,
			&i.Capacity,
			&i.CurrentLoad,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDomains = `-- name: ListProjectDomains :many
SELECT pd.id, pd.project_id, pd.domain_id, d.name as domain_name, pd.prefix
FROM project_domains pd
INNER JOIN domains d ON pd.domain_id = d.id
WHERE pd.project_id = ?
`

type ListProjectDomainsRow struct {
	ID         int64  `db:"id" json:"id"`
	ProjectID  int64  `db:"project_id" json:"project_id"`
	DomainID   int64  `db:"domain_id" json:"domain_id"`
	DomainName string `db:"domain_name" json:"domain_name"`
	Prefix     string `db:"prefix" json:"prefix"`
}

func (q *Queries) ListProjectDomains(ctx context.Context, projectID int64) ([]ListProjectDomainsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectDomains, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectDomainsRow{}
	for rows.Next() {
		var i ListProjectDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DomainID,
			&i.DomainName,
			&i.Prefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUserID = `-- name: ListProjectsByUserID :many
SELECT id, user_id, name, github_repo, github_repo_id, webhook_secret, created_at, updated_at FROM projects WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByUserID(ctx context.Context, userID int64) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.GithubRepo,
			&i.GithubRepoID,
			&i.WebhookSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersByState = `-- name: ListWorkersByState :many
SELECT id, name, address, state, capacity, current_load, capabilities, last_seen_at, created_at, updated_at FROM workers WHERE state = ? ORDER BY created_at DESC
`

func (q *Queries) ListWorkersByState(ctx context.Context, state string) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, listWorkersByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.State,
			&i.Capacity,
			&i.CurrentLoad,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAllWorkers = `-- name: ResetAllWorkers :exec
UPDATE workers SET state = 'offline', updated_at = datetime('now')
`

func (q *Queries) ResetAllWorkers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAllWorkers)
	return err
}

const startDeployment = `-- name: StartDeployment :exec
UPDATE deployments SET state = 'building', started_at = datetime('now'), updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) StartDeployment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, startDeployment, id)
	return err
}

const stopDeploymentsByProjectAndPR = `-- name: StopDeploymentsByProjectAndPR :exec
UPDATE deployments SET state = 'stopped', updated_at = datetime('now'), completed_at = datetime('now')
WHERE project_id = ? AND pr_number = ? AND state NOT IN ('stopped', 'destroyed')
`

type StopDeploymentsByProjectAndPRParams struct {
	ProjectID int64 `db:"project_id" json:"project_id"`
	PrNumber  int64 `db:"pr_number" json:"pr_number"`
}

func (q *Queries) StopDeploymentsByProjectAndPR(ctx context.Context, arg StopDeploymentsByProjectAndPRParams) error {
	_, err := q.db.ExecContext(ctx, stopDeploymentsByProjectAndPR, arg.ProjectID, arg.PrNumber)
	return err
}

const updateDeploymentForRestart = `-- name: UpdateDeploymentForRestart :exec
UPDATE deployments SET state = 'queued', worker_id = NULL, container_id = NULL, error_message = NULL, attempt = attempt + 1, updated_at = datetime('now') WHERE id = ? AND state IN ('failed', 'stopped')
`

func (q *Queries) UpdateDeploymentForRestart(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentForRestart, id)
	return err
}

const updateDeploymentForStop = `-- name: UpdateDeploymentForStop :exec
UPDATE deployments SET state = 'stopped', updated_at = datetime('now'), completed_at = datetime('now') WHERE id = ? AND state NOT IN ('stopped', 'destroyed')
`

func (q *Queries) UpdateDeploymentForStop(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentForStop, id)
	return err
}

const updateDeploymentFromWebhook = `-- name: UpdateDeploymentFromWebhook :exec
UPDATE deployments SET commit_sha = ?, branch = ?, state = 'queued', preview_url = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateDeploymentFromWebhookParams struct {
	CommitSha  string         `db:"commit_sha" json:"commit_sha"`
	Branch     string         `db:"branch" json:"branch"`
	PreviewUrl sql.NullString `db:"preview_url" json:"preview_url"`
	ID         int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateDeploymentFromWebhook(ctx context.Context, arg UpdateDeploymentFromWebhookParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentFromWebhook,
		arg.CommitSha,
		arg.Branch,
		arg.PreviewUrl,
		arg.ID,
	)
	return err
}

const updateDeploymentState = `-- name: UpdateDeploymentState :exec
UPDATE deployments SET state = ?, error_message = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateDeploymentStateParams struct {
	State        string         `db:"state" json:"state"`
	ErrorMessage sql.NullString `db:"error_message" json:"error_message"`
	ID           int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateDeploymentState(ctx context.Context, arg UpdateDeploymentStateParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentState, arg.State, arg.ErrorMessage, arg.ID)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects SET name = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateProjectParams struct {
	Name string `db:"name" json:"name"`
	ID   int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject, arg.Name, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET username = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateUserParams struct {
	Username string `db:"username" json:"username"`
	ID       int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Username, arg.ID)
	return err
}

const updateWorkerLoad = `-- name: UpdateWorkerLoad :exec
UPDATE workers SET current_load = ?, last_seen_at = datetime('now'), updated_at = datetime('now') WHERE id = ?
`

type UpdateWorkerLoadParams struct {
	CurrentLoad int64 `db:"current_load" json:"current_load"`
	ID          int64 `db:"id" json:"id"`
}

func (q *Queries) UpdateWorkerLoad(ctx context.Context, arg UpdateWorkerLoadParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkerLoad, arg.CurrentLoad, arg.ID)
	return err
}

const updateWorkerState = `-- name: UpdateWorkerState :exec
UPDATE workers SET state = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateWorkerStateParams struct {
	State string `db:"state" json:"state"`
	ID    int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateWorkerState(ctx context.Context, arg UpdateWorkerStateParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkerState, arg.State, arg.ID)
	return err
}
